apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-admin-group.yaml
  - cluster-admin-group-binding.yaml

patchesJson6902:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: cluster-admins
    path: cluster-admin-demo-users.yaml
